name: gcbm-Carpathians-ubuntu-CML
on: 
  push:
    branches:
      - main
    paths:
      - Standalone_GCBM/input_database/gcbm_input.db
  pull_request:
    branches:
      - main
    paths:
      - Standalone_GCBM/input_database/gcbm_input.db

jobs:
  run-on-container:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - uses: actions/checkout@v3

      - name: Run GCBM
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 
          cd Standalone_GCBM/gcbm_project

          /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json

      - name: Compile Results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Standalone_GCBM/tools/CompileGCBMResults

          python3 compileresults.py sqlite:///../../gcbm_project/output/gcbm_output.db --output_db sqlite:///../../processed_output/compiled_gcbm_output.db
      
      - uses: actions/upload-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/compiled_gcbm_output.db

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-results-log
          path: Standalone_GCBM/logs/compile_results.log
  
  run-on-vmhost:
    runs-on: [ubuntu-latest]
    needs: run-on-container
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - uses: actions/download-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/
      - uses: actions/download-artifact@v3
        with:
          name: compiled-results-log
          path: Standalone_GCBM/logs/

      - name: Installations and renv restore
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          pip install pandas
          cd Postprocessing
          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

      - name: dvc repro - postprocessing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s postprocessing
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics diff --show-md > report.md
          echo "## Figures created" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md
        
          