name: gcbm-Carpathians-windows-CML
on: 
  push:
    branches:
      - main
    paths:
      - Standalone_GCBM/input_database/gcbm_input.db
  pull_request:
    branches:
      - main
    paths:
      - Standalone_GCBM/input_database/gcbm_input.db

jobs:
  run-on-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          pip install installation\GDAL-2.4.1-cp37-cp37m-win_amd64.whl
          del /q "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\osgeo\gdalplugins\*.*"
          
          pip install -r installation\requirements-py37.txt

      - name: Run GCBM
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          cd Standalone_GCBM/gcbm_project
          run_gcbm.bat pythonLocation

      - name: Compile results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          cd Standalone_GCBM/tools/CompileGCBMResults
          python compileresults.py sqlite:///../../gcbm_project/output/gcbm_output.db --output_db sqlite:///../../processed_output/compiled_gcbm_output.db

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/compiled_gcbm_output.db

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-results-log
          path: Standalone_GCBM/logs/compile_results.log
  
  run-on-ubuntu:
    runs-on: [ubuntu-latest]
    needs: run-on-windows
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - uses: actions/download-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/
      - uses: actions/download-artifact@v3
        with:
          name: compiled-results-log
          path: Standalone_GCBM/logs/

      - name: Installations and renv restore
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          pip install pandas
          cd Postprocessing
          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

      - name: dvc repro - postprocessing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s postprocessing
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics diff --show-md > report.md
          echo "## Figures created" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md
          