name: compiled-db-CML
on: 
  push:
    branches:
      - main
    paths:
      - Standalone_GCBM/logs/compile_results.log
      - Standalone_GCBM/processed_output/compiled_gcbm_output.db
  pull_request:
    branches:
      - main
    paths:
      - Standalone_GCBM/logs/compile_results.log
      - Standalone_GCBM/processed_output/compiled_gcbm_output.db
      
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - name: Installations and renv restore
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          pip install pandas
          cd Postprocessing
          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

      - name: dvc repro - postprocessing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s postprocessing
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics diff --show-md > report.md
          echo "## Figures created" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md       
          